### ISSUE TITLE
Edge case in example code

### ISSUE THREAD

**Issue by erelsgl** [equalshares/equalshares.net#5]
I tried the example code on the following scenario:

* Two projects with cost 510 each.
* Two agents: A votes for 1 only, B votes for 2 only.
* Budget is 1000.
* Lexicographic tie-breaking.
* Completion by increasing the budget.

The outcome is an empty budget: [], even though one project can be funded. Why?

* With B=1000, `equal_shares_fixed_budget` returns [], as  each voter's budget is 500, so no project can be funded.
* Then, `equal_shares` increases B to 1002, so each voters' budget is 501, which is still not enough for any project, so equal_shares_fixed_budget` returns [].
* B keeps increasing until it gets to 1020, then `equal_shares_fixed_budget` returns [1,2]. But the total cost is higher than the true budget of 1000. So `equal_shares` returns the last result which fits the budget, which is [].

**Comment by erelsgl** [comment]
P.S. Why is the optimal B computed by linear search and not by binary search?

**Comment by DominikPeters** [comment]
Regarding linear search: Let W(B) denote the outcome with budget B. Then unfortunately cost(W(B)) is not increasing in B; if we increase B, some new expensive projects might become affordable, but others might thereafter not be affordable anymore, decreasing the overall spending. Due to the non-monotonicity, binary search is not well-motivated, as it will in general not find the same cutoff point as the linear search.

Regarding your example, I think the code does the same thing as the formal definitions would suggest. I agree it's unfortunate that it's the empty outcome; for this example it can be fixed by switching to "Add1u" (_Repeated increase of voter budgets by 1 currency unit, followed by utilitarian completion (Add1u)_). cc @motzarcik

**Comment by erelsgl** [comment]
> Regarding linear search: Let W(B) denote the outcome with budget B. Then unfortunately cost(W(B)) is not increasing in B; if we increase B, some new expensive projects might become affordable, but others might thereafter not be affordable anymore, decreasing the overall spending. Due to the non-monotonicity, binary search is not well-motivated, as it will in general not find the same cutoff point as the linear search.

IIUC, linear search finds the *smallest* cutoff point - the smallest B such that W(B) is below the total budget and W(B+n) is above the budget. Why do we need the smallest cutoff point - why not just any cutoff point? An arbitrary cutoff point can be efficiently found by binary search.

**Comment by DominikPeters** [comment]
In an election, in my opinion we need a well defined rule, not dependent on choices by the algorithm designer (otherwise someone could justifiably complain). There is some desirability to have a smaller total budget if possible. Having a very large budget usually implies that some voters get to spend much more money than others.
